server:
  port: 8080
  context-path: /k2alpha/

spring:
  profiles:
    active: dev

  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

#  main:
#    banner-mode: "off"

  mvc:
    throw-exception-if-no-handler-found: true

#  resources:
#    add-mappings: false
#
#  mail:
#    host: smtp.163.com
#    username: 18010179602@163.com
#    password: 15903555014
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
